EVG-19681 Ensure invalid regular expressions aren't applied to logs and introduce additional validation
evergreen-ci/parsley pull request #302
Opened 2023-06-01 14:53 UTC by khelif96

EVG-19681

### Description 
It looks like this bug was caused by some users accessing a broken parsley link which may have had a broken regular expression in the URL. Since the regular expression was invalid it would throw an error when we tried to build it in the `constructRegexToMatch` function. 
* This PR adds some error handling and reporting to `constructRegexToMatch`.
* Also updates the side nav to show the errored regular expression and provides a path for users to fix it. 

### Screenshots
![image](https://github.com/evergreen-ci/parsley/assets/4605522/91391df7-dc8d-4d02-b829-2d91e3db2035)
<img width="365" alt="image" src="https://github.com/evergreen-ci/parsley/assets/4605522/3c0ee66d-b060-4dbd-974e-a37ac303b18e">

https://github.com/evergreen-ci/parsley/assets/4605522/491b0b21-7394-40bb-be9b-459f6bf4fac5

### Testing 
Replicated the error locally and wrote some tests to fix it.

2023-06-01 15:32 UTC, sophstad requested changes

2023-06-01 15:32 UTC, sophstad commented on src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/index.tsx
> +    // setIsValid(true);
```suggestion
```

2023-06-01 15:32 UTC, sophstad commented on src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/index.tsx
> +          <Badge>FILTER</Badge>
[nit] The badge applies capitalization itself
```suggestion
          <Badge>Filter</Badge>
```

2023-06-01 20:55 UTC, khelif96 commented
Did some refactoring to surface the errors regardless of the scenario.

2023-06-05 13:13 UTC, sophstad commented on src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/index.tsx
> +          <Badge>FILTER</Badge>
Bump

2023-06-05 13:21 UTC, sophstad approved these changes
A few small notes but LGTM!

2023-06-05 13:21 UTC, sophstad commented on src/utils/validators/index.ts
> +    console.log(e.message);
```suggestion
```

2023-06-05 13:21 UTC, sophstad commented on src/utils/validators/index.ts
> +    const message = e.message.replace(
[nit] Could be helpful to mention we're removing this string from the beginning of the error message

2023-06-05 13:21 UTC, sophstad commented on src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/index.tsx
> +          <Badge>FILTER</Badge>
Bump

2023-06-05 18:55 UTC, merged