DEVPROD-803 Add support for copying and pasting logs into parsley
evergreen-ci/parsley pull request #501
Opened 2024-03-05 20:43 UTC by khelif96

DEVPROD-803

### Description 
Adds support to copy and paste files into Parsley from the upload page. 
Went against the approach of including a text box because the UX didn't work and pasting a large file into a text box causes the browser to freeze up.

### Screenshots
![image](https://github.com/evergreen-ci/parsley/assets/4605522/3b085a50-99c6-49cd-b616-9ee9be8c1fa9)

### Testing 
Unit tests.
I'm still figuring out how to write cypress tests since the paste event doesn't seem to be supported

2024-03-07 14:49 UTC, sophstad requested changes
I encountered this error in Firefox when I tried pasting
<img width="496" alt="image" src="https://github.com/evergreen-ci/parsley/assets/9298431/77ed7b28-01e1-455e-bb79-45d704b9e613">

2024-03-07 14:59 UTC, minnakt reviewed
Could we remove "into parsley" from the PR title? (since the repo is Parsley, we implicitly know the feature is being added to Parsley 😁)

2024-03-07 14:59 UTC, minnakt commented on src/analytics/logDrop/useLogDropAnalytics.ts
> +  | { name: "Pasted text" }
maybe it could be "pasted text from clipboard"

2024-03-07 14:59 UTC, minnakt commented on src/pages/LogDrop/ParseLogSelect/index.tsx
> +  isPastedFile: boolean;
nit. prefer `isPastedText`, since it's not a true file

2024-03-07 14:59 UTC, minnakt commented on src/pages/LogDrop/ParseLogSelect/index.tsx
> +          "the pasted file"
```suggestion
          "the pasted text"
```

2024-03-07 14:59 UTC, minnakt commented on src/pages/LogDrop/FileDropper.tsx
> +                  setFileName("Pasted Log");
Possibly shouldn't set file name, since it's not a file

2024-03-18 19:02 UTC, khelif96 commented
I'm gonna close this branch so it doesn't get stale. Once firefox releases support for this feature we can reopen it!

2024-03-18 19:02 UTC, closed without merging