EVG-18195: Fix double scrollbar issue
evergreen-ci/parsley pull request #95
Opened 2022-11-01 19:04 UTC by minnakt

EVG-18195

### Description 
This PR removes the double scrollbar that was appearing in the `Y` direction. We were using `overflow` styling on the list container but we only really need `overflow-x` to enable horizontal scrolling.

Note that the scrollbars will still appear visually different between mouse and trackpad. This is more a responsibility for the user, as they will need to change their scrolling settings to the following under General in System Preferences:

<img width="457" alt="Screen Shot 2022-11-01 at 2 53 01 PM" src="https://user-images.githubusercontent.com/47064971/199314759-a3725177-8a29-4aab-9996-99f4e71ff72a.png">

Perhaps we can put this in a FAQ somewhere, although it is a Mac specific setting.

### Another unrelated problem
I noticed a separate bug that occurs when you have a filter applied with wrap enabled. When I wrote the expand rows PR, I made it so that collapsed rows are roughly same size as a normal size row so that we wouldn't have to refresh the cache.

However I forgot that that rows could be larger than the default size due to wrapping. Because the cache is never refreshed, that leads to visual effects like in the following screenshot:

<img width="1443" alt="Screen Shot 2022-11-01 at 1 19 57 PM" src="https://user-images.githubusercontent.com/47064971/199315453-4c113140-0d52-44b7-acb7-af7742becd58.png">

To try it out yourself, visit [this link](https://parsley-beta.corp.mongodb.com/resmoke/7e208050e166b1a9025c817b67eee48d/test/1716e11b4f8a4541c5e2faf70affbfab?bookmarks=0,11079&filters=100heartbeat&wrap=true) and expand the first collapsed row.

Unfortunately this means we will need to refresh the entire cache and reset row heights when we uncollapse rows. This introduces a regression in behavior because now the scroll is going to jump all over the place again. The jump is particularly horrible on wrapped resmoke logs. And again, we can't avoid this because of this library we are using. 😔🧍😭

### Screenshots
- N/A

### Testing
- Fixed stories which had been showing incorrect behavior when applying wrap and expanding rows.

2022-11-01 21:20 UTC, khelif96 requested changes

2022-11-01 21:20 UTC, khelif96 commented on src/components/LogPane/index.tsx
> +  }, [
I'm noticing a strange jump when i expand a line now. 

https://user-images.githubusercontent.com/4605522/199344011-2a76d66f-8e34-4219-af68-047b2183300e.mov

2022-11-02 17:41 UTC, sophstad approved these changes

2022-11-07 15:16 UTC, khelif96 approved these changes
TY

2022-11-07 15:40 UTC, merged